spring.application.name=ibom-api
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ibom?serverTimezone=UTC
spring.datasource.username=${IBOM_USERNAME}
spring.datasource.password=${IBOM_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

app.auth.jwt.secret=${IBOM_JWT_SECRET}
app.auth.jwt.access-token-ttl-seconds=900
app.auth.refresh-token-ttl-seconds=604800

app.auth.registration.allowed-domains=${IBOM_REGISTRATION_ALLOWED_DOMAINS:fsoft.com.vn,fpt.com.vn,fpt.com,gmail.com}
app.mail.executor.core-pool-size=2
app.mail.executor.max-pool-size=4
app.mail.executor.queue-capacity=100

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${IBOM_SMTP_USERNAME}
spring.mail.password=${IBOM_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
