package com.fpt.ibom.exception;

public enum ErrorCode {
	AUTH_INVALID_CREDENTIALS,
	AUTH_ACCOUNT_INACTIVE,
	AUTH_INVALID_OR_EXPIRED_VERIFICATION_CODE,
	AUTH_VERIFICATION_CODE_REQUEST_LIMIT_REACHED,
	AUTH_EMAIL_ALREADY_REGISTERED,
	AUTH_USERNAME_ALREADY_REGISTERED,
	AUTH_EMAIL_OR_USERNAME_ALREADY_REGISTERED,
	AUTH_INVALID_REFRESH_TOKEN,
	AUTH_INCORRECT_CURRENT_PASSWORD,
	AUTH_USERNAME_CONFLICT,
	AUTH_EMAIL_DOMAIN_NOT_ALLOWED,
	VALIDATION_ERROR,
	REQUEST_FAILED,
	INTERNAL_SERVER_ERROR
}
