ALTER TABLE profiles
    MODIFY COLUMN full_name VARCHAR(255) NULL,
    MODIFY COLUMN email VARCHAR(255) NULL,
    MODIFY COLUMN phone_number VARCHAR(50) NULL,
    MODIFY COLUMN address VARCHAR(500) NULL,
    MODIFY COLUMN first_name VARCHAR(100) NULL,
    MODIFY COLUMN last_name VARCHAR(100) NULL,
    MODIFY COLUMN job_title VARCHAR(100) NOT NULL,
    MODIFY COLUMN personality VARCHAR(4000) NULL,
    MODIFY COLUMN technical_summary VARCHAR(4000) NULL;
